### ISSUE TITLE
Secondary Buttons

### ISSUE THREAD

**Issue by artsheeps** [sumup/circuit-ui#30]

**Comment by melmdesign** [comment]
![image](https://user-images.githubusercontent.com/24547232/35438979-30ee0966-0299-11e8-9a30-548c26808d9e.png)

Styling for secondary buttons has also been added ☝️ 

They can be found on the Abstract page linked [here](https://share.goabstract.com/eea571c7-0e1e-45d9-a3d7-cc75c13694b5)

These buttons replicate default buttons in terms of spacing, font size etc. But styling is stripped from the button background. Only exception being the "focus" state which uses the same border as a default focused button.

**Comment by felixjung** [comment]
Friends, I don't really know what to think about this 😞. Do I understand this correctly that this button style is going to be used for secondary buttons on both flat (marketing) and UI (Dashboard) contexts? And that it will look the same?

I find it a bit inconsistent that buttons will look identical when we render them with different `variant` props. For example:

```javascript
<Button variant="primary" flat />

// and

<Button variant="secondary" flat />
```

would both return the same button. I would think that our modifiers should cause buttons to look different. Otherwise, do they really mean that much?

At least after looking at the button code again, I find it hard to abstract the various behaviors into one component, because they are not mutually exclusive. There seems to be to much mixing going on.

Also, it would really help, if these things came with more context. At least the three button combinations next to each other, somehow highlighting the differences. 👍

**Comment by felixjung** [comment]
Looking at how the buttons in Polaris work... Maybe it's not the issue that we have too many variants, but that the naming/triggering is not clear. Do you have any ideas regarding naming? If we can split this into default, flat, secondary or something, maybe that will be clearer. Also, don't we also need text buttons? What would those look like and how would they fit in here?

**Comment by artsheeps** [comment]
Felix already discussed this with Liam earlier, but here again as a quick summary:
The standard UI Button will be the default. Variations can be flat and secondary, while the secondary is the same as the old text button. By using the same paddings as the other two versions we just simplify there usage, so that they can be put next to each other without having to be positioned.
