### ISSUE TITLE
[Info] How do you do static extraction?

### ISSUE THREAD

**Issue by eatsjobs** [sumup/circuit-ui#306]
Hi, awesome work! I'm writing a design system for my company and I'm evaluating some css-in-js options. Emotion has deprecated extractStatic. I saw you have a script to generate the extraction of css in a separate file but I have doubt: how do you remove the css in the component to avoid repetition?

Thanks in advance

**Comment by mlent** [comment]
@eatsjobs One point of clarification -- static CSS extraction is only meant to be used in non-React apps (i.e. HTML/CSS-only web pages). For React apps you obviously don't need it because it'll be injected for you. So you should not be in any scenario where you have duplicate CSS from the component because you only use extracted CSS when you _cannot_ use the React components. Does that help?

**Comment by eatsjobs** [comment]
@mlent Yes. thanks for the response.

**Comment by fernandofleury** [comment]
Hey @eatsjobs I'll close the issue since the question seems to be answered now. Please feel free to reopen if you have any other questions!
